Build of [TPL_REPO_FULL_NAME]@[TPL_COMMIT_BRANCH] by [TPL_AUTHOR_NAME]
<font color=[TPL_STATUS_COLOR]>[TPL_BUILD_STATUS]</font> in [TPL_BUILD_CONSUMING]s [TPL_STATUS_EMOTICON]

[TPL_COMMIT_MSG]

[[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])

[click to the drone build page]([TPL_BUILD_LINK])